### ISSUE TITLE
Jq extra functions missing

### ISSUE THREAD

**Issue by Jiehong** [quarkiverse/quarkus-jackson-jq#68]
Hello there,

The following dependency could also be added for some extra functions:

```
<dependency>
      <groupId>net.thisptr</groupId>
      <artifactId>jackson-jq-extra</artifactId>
      <version>${jackson-jq.version}</version>
    </dependency>
```

(Source: https://github.com/eiiches/jackson-jq#using-jackson-jqextras-module)

So that those functions are correctly registered for reflection as well.

WDYT?

**Comment by Jiehong** [comment]
I just tried something, and adding this as a dependency seems to work, even without registering for reflection.

Wondered why, and it seems that this extension finds all `BuiltinFunctions` (https://github.com/quarkiverse/quarkus-jackson-jq/blob/main/deployment/src/main/java/io/quarkiverse/jackson/jq/deployment/JacksonJqProcessor.java#L59), and the jq extra functions are all annotation (eg: https://github.com/eiiches/jackson-jq/blob/develop/1.x/jackson-jq-extra/src/main/java/net/thisptr/jackson/jq/extra/functions/HostnameFunction.java#L21), and so it works just fine.

I can create a PR to simply add the extra as a dependency in this extension then, and that should be enough.

**Comment by ricardozanini** [comment]
If only adding the extras dependency work, we can add a new module `-extras` (runtime AND deployment) here. So users pick their favorite. 

Not sure if adding the extras in the main module is a good idea since some use cases might not leverage from it. They are kept in the extras by the underlying library for a reason. I think it's a reasonable approach to do the same here.
